layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  employment: https://researchprofiles.ku.dk/en/persons/valentina-s-espinoza-fern%C3%A1ndez
  researchgate: Valentina-Espinoza-2

topics:
  - name: Ergonomic Keyboards
    web_url: https://github.com/ValeEspinozaF/UFO_splitkb
    image_url: https://github.com/ValeEspinozaF/personal-website/blob/master/assets/images/UFO_keyboard.PNG

#  - name: Web design

#  - name: Sass
#    web_url: https://github.com/topics/sass
#    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
